plugins {
    alias(libs.plugins.sudokutrio.jvm.library)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.pitest)
    `java-test-fixtures`
}

dependencies {
    api(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.serialization.json)

    testFixturesImplementation(libs.kotlinx.coroutines.core)
}

kover {
    reports {
        verify {
            rule("Domain line coverage") {
                minBound(90)
            }
        }
    }
}

pitest {
    junit5PluginVersion.set(libs.versions.pitestJunit5)
    targetClasses.set(listOf("io.github.vinaooo.sudokutrio.domain.*"))
    // Generated by kotlinx.serialization; covered by round-trip tests instead.
    excludedClasses.set(listOf("*\$\$serializer"))
    timeoutConstInMillis.set(10_000)
    threads.set(2)
    jvmArgs.set(listOf("-Xmx512m"))
    outputFormats.set(listOf("HTML", "XML"))
    timestampedReports.set(false)
    mutationThreshold.set(80)
    coverageThreshold.set(90)
}

// Measures puzzle generation per mode (time, givens, difficulty hit rate, uniqueness), outside the test task.
tasks.register<JavaExec>("benchmarkGenerator") {
    classpath = sourceSets["test"].runtimeClasspath
    mainClass.set("io.github.vinaooo.sudokutrio.domain.generator.GeneratorBenchmarkKt")
    args((project.findProperty("seeds") as String?) ?: "30")
}
